---
title: "From Reproducible to Reusable"
subtitle: "NHS RPySOC"
description: "Maybe code utopia isn't too far away"
date: 2024-11-22
categories: [conference, rap, data science]
image: "featured.svg"
img-alt: "PYSOC conference 2024 banner."
draft: false
---

## Abstract

The rise of open-source projects in healthcare is inspiring, with analysts increasingly adopting Reproducible Analytical Pipelines (RAP) and sharing their code openly with pride. However, despite this, the reuse of code across organisations remains surprisingly low. Many valuable scripts and packages stagnate in GitHub repositories, while teams reinvent the wheel, starting their analyses from scratch.


This raises critical questions: Are we creating tools that are insufficiently modular or user-friendly? Is the importance of reusability underappreciated? Or is the challenge simply in discovering existing code and recognising its relevance?


As a newcomer to the NHS, I've engaged in conversations with analysts and data scientists to better understand these challenges and to promote the reuse of code across teams and organisations. In this talk, I will share insights from these discussions and offer practical tips on how to put the reusable into RAP.

## Slides

<p align="center">
<iframe src="https://statsrhian.github.io/nhsrpysoc-reusable" width="100%" height = "400px"></iframe>
</p>

## Recording

<iframe width="560" height="315" src="https://www.youtube.com/embed/s21lNo3pZVQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


## Links

- [Slides](https://statsrhian.github.io/nhsrpysoc-reusable)

- [NHS-R Community](https://nhsrcommunity.com/)

