---
title: "What I’m doing now"
---

_Updated 2025-08-29. Inspired by [Derek Sivers](https://nownownow.com/about)._

I’ve had a lovely summer travelling around Scotland in my campervan and spending plenty of time on the water kayaking. Now, I’m looking forward to a cosy autumn, contributing to community projects and playing [games](https://steamcommunity.com/id/thetrianglegirl/).

This season I want to give more energy to community work. I’ve recently joined the leadership team for [rainbowR](https://rainbowr.org), and we’re meeting in person to think about how to grow the community and shape our first conference. I’m also hoping to spend more time supporting the [NHS-R Community](https://nhsrcommunity.com/conference.html).

Outside of work, I’ve started a small community paddling group, Canny Paddlers, and we’re organising a kayak symposium in Northumberland next May.

In work, I’d like to settle into a routine, prioritising morning beach walks and some weekly time for reflection. I’m also aiming to complete my [Advanced Data Science Professional](https://rss.org.uk/membership/professional-development/advanced-data-science-professional/) award. I’ve got a handful of conferences ahead. I’m looking forward to catching up with awesome, inspiring folk, in person. If you’re at any of these, come say hi 👋

- Sept: [RSS Conference](https://rss.org.uk/training-events/conference-2025/)
- Oct: [Shiny in Production](https://shiny-in-production.jumpingrivers.com/)
- Nov: [NHS-R conference](https://nhsrcommunity.com/conference.html)
- Dec: [HACA conference](https://haca-conference.nhs.uk/) (online)





