---
title: "Better Together: Supporting Analysts and Managers with RAP"
subtitle: "HACA conference"
description: "Sharing findings and tips from running NHS RAP drop-ins"
date: 2025-12-04
categories: [conference, rap]
image: "featured.svg"
img-alt: "Illustration of two people sat at a laptop pair programming"
---

## Abstract

Many health and care analysts work alone, trying to implement reproducible analytical pipelines (RAP) without much local support. To help, The Strategy Unit has been running regular RAP drop-ins. These sessions provide a supportive space where both analysts and managers can share challenges, swap tips, and ask the “silly” questions without judgement.

Questions often repeat, from convincing IT to allow new tools, to learning Git, to handling concerns about patient-identifiable data. What makes the sessions work is not having all the answers, but connecting people and learning together.

This talk will share the common themes we’ve heard so far, the lessons that have emerged, and how creating open, welcoming spaces helps make RAP more sustainable across the NHS.

## Slides

<p align="center">
<iframe src="https://statsrhian.github.io/better-together" width="100%" height = "400px"></iframe>
</p>

## Recording

<iframe width="560" height="315" src="https://www.youtube.com/embed/JynQkEFkGv0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share " allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>


## Links

- [Slides](https://statsrhian.github.io/better-together)

- [Health and Care Analytics Conference 2025](https://haca-conference.nhs.uk/)
